# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['feature-codecov']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Configure CI
        run: npm ci
      - name: Build solution
        run: npm run build
      - name: Start smoke tests
        run: npm run test-smoke
      - name: Start unit tests
        run: npm run test
      - uses: codecov/codecov-action@v3
        with:
          files: nyc_output/processinfo/*.json
          flags: unittests # optional
          name: codecov-unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
